### ISSUE TITLE
Method client.Client.request does not propagate HTTP status code when errors are found in json response

### ISSUE THREAD

**Issue by marquesds** [messagebird/python-rest-api#15]
[Documentation](https://developers.messagebird.com/docs/errors) says: `"In case of an error, the body of the response includes a json formatted response that tells you exactly what is wrong."`, but once this API raises an ErrorException with json response error codes it also suppress response's HTTP status code, as you can see: https://github.com/messagebird/python-rest-api/blob/master/messagebird/client.py#L58

**Comment by epels** [comment]
Hi @marquesds, thank you for opening an issue!

It is correct - and intentional - the HTTP status code is suppressed: the clients/SDKs are meant to abstract away (transport) details like that. As described in the [documentation](https://developers.messagebird.com/docs/errors), everything you need to know can be derived from MessageBird's error codes. For example: if the resource is not found, we'll return HTTP 404, but the response will also have an error with code `20`.

Please don't hesitate to message me if you have any questions about this - thanks!
